<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-R4GDRCNDCX"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-R4GDRCNDCX');
</script>

title: Shivangi Khare # your name (or website title) here

logo: "/images/Pic.jpg?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)

  M.Tech. student at <a href="http://cds.iisc.ac.in/"> Department of Computational & Data Sciences </a> 
  <br>
  <a href="https://iisc.ac.in/">IISc Bangalore</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/shivangi-khare/">View My LinkedIn Profile</a> <br>
  <a href="https://drive.google.com/file/d/0B51dNZ5p9N4JNEg4dF9CN09nNzA/view?usp=sharing">View My Resume</a> <br>
    
theme: jekyll-theme-minimal
# google_analytics: G-R4GDRCNDCX # your Google Analytics tracking ID here
