title: Shivangi Khare # your name (or website title) here
logo: "/images/Pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  M.Tech. student at Department of Computational & Data Sciences 
  <br><br>
  IISc Bangalore
  <br><br>
  <a href="https://www.linkedin.com/in/shivangi-khare/">View My LinkedIn Profile</a> 
  <a href="https://github.com/shivangikhare5">View My GitHub Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-R4GDRCNDCX # your Google Analytics tracking ID here
