title: Shivangi Khare # your name (or website title) here

logo: "/images/Pic.jpg?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)

  M.Tech. student at <a href="http://cds.iisc.ac.in/"> Department of Computational & Data Sciences </a> 
  <br>
  <a href="https://iisc.ac.in/">IISc Bangalore</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/shivangi-khare/">View My LinkedIn Profile</a> <br>
  <a href="https://github.com/shivangikhare5">View My GitHub Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-R4GDRCNDCX # your Google Analytics tracking ID here
